### ISSUE TITLE
Enhance update-readme-issue.yml to cover ecosystem-wide updates

### ISSUE THREAD

**Issue by toshi0806** [toshi0806/texlive-ja#29]
## 概要
現在の `update-readme-issue.yml` はREADME更新のIssueのみを作成していますが、エコシステム全体の更新を考慮した拡張を検討する。

## 現状
- texlive-ja-textlintの新バージョンリリース時、README更新のIssueのみ作成
- 下流プロジェクト（latex-environment等）の更新は手動で管理

### 案1: 単一Issueに全更新タスクを含める
```yaml
body: |
  ## 📝 Ecosystem Update Required
  
  ### texlive-ja-textlint
  - [ ] Update README.md version references
  
  ### latex-environment
  - [ ] Update base image version in devcontainer.json
  - [ ] Test with new image
  - [ ] Create release if needed
  
  ### Other templates
  - [ ] Check compatibility
  - [ ] Update if necessary
```

### 案2: 複数の独立したIssueを作成
```yaml
# README更新Issue
- title: Update README.md for ${tagName}
  labels: ['documentation']

# latex-environment更新Issue  
- title: Update latex-environment to use ${tagName}
  labels: ['ecosystem', 'dependency']
  repo: latex-environment

# 他のテンプレート更新Issue
- title: Check template compatibility with ${tagName}
  labels: ['ecosystem', 'testing']
```

### 案1（単一Issue）
- ✅ 全体の進捗が一目で分かる
- ❌ Issue が大きくなりすぎる可能性

### 案2（複数Issue）
- ✅ 各タスクが独立して管理可能
- ✅ 適切なリポジトリにIssueを作成可能
- ❌ 複数リポジトリへの権限が必要

## 実装の考慮事項
- クロスリポジトリでのIssue作成権限
- 更新の必要性を自動判定するロジック
- エコシステムの依存関係の管理

## 関連情報
- エコシステムのアーキテクチャ: thesis-environment/ECOSYSTEM.md
- 現在の更新フロー: 手動での依存関係確認

このIssueでアプローチを決定後、実装に着手する。
